### user signup
POST http://localhost:8080/users/signup
Content-Type: application/json

{
  "email": "1443424326@qq.com",
  "password": "hello#world123",
  "confirm_password": "hello#world123"
}

### user login
POST http://localhost:8080/users/login
Content-Type: application/json

{
  "email": "1443424326@qq.com",
  "password": "hello#world123"
}

### user profile
GET http://localhost:8080/users/profile
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2OTc1NjA2NjYsIlVpZCI6MX0.S-Ne743iIRVS1LofEMFvifuLet2k-WGUobTWrETBeFCnGWSCkckukVT-yr6gGQwfOUICoXeKZHxKaciezAWPkg

### user edit
PUT http://localhost:8080/users/edit
Content-Type: application/json

{
  "nickname": "mercycrazy",
  "birthday": "2021-02-11",
  "about_me": "cool"
}
